name: Feature request
description: Suggest an idea for @arxis/api.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem do you want to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: How would you like the API to look?
      render: ts
